# Task
Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

1.Logistic Regression

2.SVM

3.Decision Tree

4.Random Forest

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np


In [9]:
iris = load_iris()

In [10]:
dir(iris)

['DESCR',
 'data',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

Logistic Regression

In [11]:
log = cross_val_score(LogisticRegression(), iris.data, iris.target)
log

C:\Users\kimani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [12]:
np.average(log)

0.9733333333333334

Decision tree


In [13]:
decision = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
decision

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [14]:
np.average(decision)

0.9600000000000002

Support vector machine


In [15]:
support = cross_val_score(SVC(), iris.data, iris.target)
support

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [17]:
np.average(support)

0.9666666666666666

Random Forest


In [40]:
rf = cross_val_score(RandomForestClassifier(n_estimators= 100), iris.data, iris.target)
rf

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [41]:
np.average(rf)

0.9666666666666668

Best Score is for Logistic with: 0.9733333333333334