In [5]:
import numpy as np
a = np.array([5,6,9])

a[0]
a[1]
a.ndim

1

In [7]:
a = np.array([[1,2], [3,4], [5,6]])
a.ndim
a.itemsize
a.dtype

dtype('int32')

In [13]:
a = np.array([[1,2], [3,4], [5,6]], dtype = np.float64)
a.itemsize
a
a.size
a.shape

(3, 2)

In [14]:
a = np.array([[1,2], [3,4], [5,6]], dtype = complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [21]:
import numpy as np
np.zeros( (3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
# l = range(5)
# l
# l[-1]
np.arange(1,5)
np.arange(1,5,2)
np.linspace(1,5,10)
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [46]:
import numpy as np
a = np.array([[1,2], [3,4], [5,6]])
a
a.shape
a.reshape(2,3)
a.reshape(6,1)
a.ravel()
a
a.min()
a.max()
a.sum()
a.sum(axis=0)
a.sum(axis=1)
np.sqrt(a)
np.std(a)

1.707825127659933

In [53]:
import numpy as np
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a
b
a + b
a.dot(b)

array([[19, 22],
       [43, 50]])