Loss or a cost function is an important concept we need to understand if you want to grasp how a neural network trains itself. We will go over various loss functions in this video such as mean absolute error (a.k.a MAE), mean squared error (a.k.a MSE), log loss or binary cross entropy. After going through theory we will implement these loss functions in python. It is important to go through this implementation as it might be useful during your interviews (if you are targeting a role of a data scientist or a machine learning engineer)

use log loss for logistic regression and not MSE

In [2]:
import numpy as np


In [3]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

# implement mean absolute error function

In [6]:

# average absolute difference between true and prediicted value
def mae(y_true, y_predicted):
    total_error = 0
    # run forloop parallel in two arrays
    for yt, yp in zip(y_true, y_predicted):
        total_error += abs(yt - yp)
    # print total error
    print("Total Error: ", total_error)

    mae = total_error / len(y_true)
    # print mean absolute error
    print("MAE: ", mae)
    return mae


In [7]:
mae(y_true, y_predicted)

Total Error:  2.5
MAE:  0.5


0.5

### usee numpy to obtain the same

In [10]:

np.mean(np.abs(y_predicted - y_true))

0.5

# Implement Log Loss or Binary Cross Entropy

In [12]:
np.log([0.0000000000000000000000000000000000000000001])

array([-99.011159])

In [13]:
eplison = 1e-15

In [14]:
y_predicted

array([1, 1, 0, 0, 1])

In [16]:
# replace ones and zeros using list comprehension
# first replace zeros"
y_predicted_new = [max(i, eplison) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [17]:
# now replace ones
y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]
y_predicted_new


[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [18]:
# cnvert y_predicted_new tonumpy array
y_predicted_new = np.array(y_predicted_new)
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [20]:
# formula for log loss
-np.mean(y_true * np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [21]:
def log_loss(y_true, y_predicted):
    y_predicted_new =[max(i, eplison) for i in y_predicted]
    y_predicted_new = [min(i, 1-eplison) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true * np.log(y_predicted_new) + (1-y_true)*np.log(1-y_predicted_new))

In [22]:
log_loss(y_true, y_predicted)

17.2696280766844

# impelement mean square error

#### without using numpy


In [23]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt - yp)**2
    print("Total Squared Error: ", total_error)
    mse = total_error / len(y_true)
    print("Mean Squared Error: ", mse)
    return mse

In [24]:
mse(y_true, y_predicted)

Total Squared Error:  1.83
Mean Squared Error:  0.366


0.366

#### using numpy

In [25]:
np.mean(np.square(y_true - y_predicted))

0.366