how exactly word embeddings are computed?. There are two techniques for this (1) supervised learning (2) self supervised learning techniques such as word2vec, glove. In this tutorial we will look at the first technique of supervised learning.

Supervised learning
take an  NP problem and try to solve it.As a side effect, you get word embeddings

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [3]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:
# convert a review into one hot encoded
one_hot("amazing restaurant", 30)

[22, 2]

In [8]:
vocab_size= 30
# encode all reviews
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews


[[18, 26],
 [22, 2],
 [20, 13],
 [10, 14, 26],
 [9, 14, 26],
 [28, 26],
 [21, 14, 3],
 [24, 9],
 [24, 28],
 [14, 26]]

In [10]:
# padding to have uniform lengths
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen= max_length, padding= 'post')
print(padded_reviews)

[[18 26  0]
 [22  2  0]
 [20 13  0]
 [10 14 26]
 [ 9 14 26]
 [28 26  0]
 [21 14  3]
 [24  9  0]
 [24 28  0]
 [14 26  0]]


In [15]:
# create an embeded vector size
embedded_vector_size = 4

# create model
model = Sequential()
model.add(Embedding(vocab_size, embedded_vector_size, input_length= max_length, name= "embedding"))
model.add(Flatten())
model.add(Dense(1, activation= 'sigmoid'))

In [12]:
X = padded_reviews
y = sentiment

In [16]:
# compille model
model.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X, y, epochs= 50, verbose= 0)

In [19]:
loss, accuracy= model.evaluate(X, y)
accuracy



1/1 [==============================] - 1s 1s/step - loss: 0.6479 - accuracy: 1.0000


1.0

In [21]:
# see weights
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [23]:
weights[11]

array([-0.00899423, -0.01363624, -0.04190633, -0.00486615], dtype=float32)

In [24]:
weights[3]

array([-0.08104215, -0.07815223,  0.02746135, -0.05781384], dtype=float32)