# Machine Learning Tutorial Python - 3: Linear Regression Multiple Variables(multivariate regression) 

### price = m1*area + m2*bedrooms + m3*age + b
### price = dependent variable
###  area, age, bedroom = independent(features)
### m1, m2, m3 = coefficient
### b = intercept
### generalized as, y = m1x1 + m2X2 + m3x3 + b

# Data processing,handling missing data point

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model


In [3]:
df = pd.read_csv("homeprices_ML3.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [7]:
# handling the missing value in bedrooms column
# use median()
# use median a an integer,math.floor()
import math
median_bedroooms = math.floor(df.bedrooms.median())
median_bedroooms


4

In [9]:
# filling the NaN values
df.bedrooms = df.bedrooms.fillna(median_bedroooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

# training the model

In [10]:
# creatiing the model
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']], df.price)

LinearRegression()

In [11]:
# check coefficients
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [12]:
# checking the intercept
reg.intercept_

221323.00186540425

In [20]:
#predict
# 3000sqr ft area , 3 bedrroms, 40yr old

reg.predict([[3000,3,40]])

array([498408.25158031])

In [21]:
# explanation
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540425

498408.25157402427

In [23]:
# 2500 sqr ft area , 4 bedrooms,5 yr old
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [24]:
# explanation
112.06244194*2500 + 23388.88007794*4 + -3231.71790863*5 + 221323.00186540425

578876.0374840143

# excercise


### use hiring_ML3.csv

### use python word2number module


### Exercise
### In exercise folder (same level as this notebook on github) there is hiring.csv. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,

### 2 yr experience, 9 test score, 6 interview score

### 12 yr experience, 10 test score, 10 interview score