# Machine Learning Tutorial Python 12 - K Fold Cross Validation

Many times we get in a dilemma of which machine learning model should we use for a given problem. KFold cross validation allows us to evaluate performance of a model by creating K folds of given dataset. This is better then traditional train_test_split. In this tutorial we will cover basics of cross validation and kfold. We will also look into cross_val_score function of sklearn library which provides convenient way to run cross validation on a model

###### wys to train your model
###### 1.use all available data for training and test on same dataset
###### 2.split available dataset into training and test sets
###### 3.k-fold crossvalidation
 

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [13]:
# splitting data set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

# different classifiers

In [8]:
# using logistic regression
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

C:\Users\kimani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [16]:
# using SVM
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9944444444444445

In [15]:
# using random forest
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9814814814814815

# USING K FOLD

In [17]:
# using k -fold API
from sklearn.model_selection import KFold
# creating three folds
kf = KFold(n_splits= 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [18]:
# using kfold on dataset
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [20]:
# using kfold on our digits example
# create a generic method
# takes model as an input

def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [22]:
# using method to get scores of different  clasifiers
get_score(LogisticRegression(), x_train, x_test, y_train, y_test)

C:\Users\kimani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [23]:
get_score(SVC(), x_train, x_test, y_train, y_test)

0.9944444444444445

In [25]:
from sklearn.model_selection import StratifiedKFold
# divides all categories in a uniform way
folds = StratifiedKFold(n_splits= 3)

In [35]:
# explain how kfold works
# prep scores arrays of diffeerent models
scores_l = []
scores_svm = [] 
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]
    # measure performance of three or four models in eeach iteration
    # then append to array
    scores_l.append(get_score(LogisticRegression(), x_train, x_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    # increase number of trees in random forest,n_estimators=40
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))


C:\Users\kimani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\kimani\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_ite

In [29]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [30]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [34]:
scores_rf

[0.9282136894824707, 0.9432387312186978, 0.9265442404006677]

In [36]:
# doing the above with inbuilt method of sklearn.
from sklearn.model_selection import cross_val_score


# logistic regresiion
cross_val_score(LogisticRegression(solver='liblinear'), digits.data, digits.target,cv=3)

In [48]:
# SVC
cross_val_score(SVC(gamma= 'auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [51]:
# random forest
cross_val_score(RandomForestClassifier(n_estimators= 40), digits.data, digits.target, cv=3)

array([0.92654424, 0.95659432, 0.9081803 ])

In [53]:
# parameter tuning
# random forest
cross_val_score(RandomForestClassifier(n_estimators= 5), digits.data, digits.target, cv=3)

array([0.84140234, 0.83639399, 0.85308848])

In [54]:
# random forest
cross_val_score(RandomForestClassifier(n_estimators= 15), digits.data, digits.target, cv=3)

array([0.9148581 , 0.92320534, 0.9015025 ])

In [55]:
# random forest
cross_val_score(RandomForestClassifier(n_estimators= 50), digits.data, digits.target, cv=3)

array([0.93489149, 0.94490818, 0.92821369])

In [56]:
# random forest
cross_val_score(RandomForestClassifier(n_estimators= 60), digits.data, digits.target, cv=3)

array([0.93656093, 0.94490818, 0.92821369])

# exercise

###### Use iris flower dataset from sklearn library and use cross_val_score against following models to measure the performance of each. In the end figure out the model with best performance,

###### 1.Logistic Regression
###### 2.SVM
###### 3.Decision Tree
###### 4.Random Forest